WITH CTE AS (
    SELECT SUM(FH.TOTAL_ORDER) AS SF, FH.FLAVOR AS FLAVOR, SUM(J.TOTAL_ORDER) AS SJ
    FROM FIRST_HALF FH
    INNER JOIN JULY J 
    ON FH.FLAVOR = J.FLAVOR
    GROUP BY J.FLAVOR
)

SELECT FLAVOR
FROM CTE
ORDER BY SF + SJ DESC
LIMIT 3
;