-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P 
RIGHT JOIN  APPOINTMENT A ON P.PT_NO = A.PT_NO
LEFT JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID 
WHERE A.APNT_CNCL_YN = 'N' AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD;