WITH SHORTLIST AS (
    SELECT FP.CATEGORY, MAX(FP.PRICE) AS MAX_PRICE, FP.PRODUCT_NAME
    FROM FOOD_PRODUCT FP
    WHERE FP.CATEGORY IN('과자', '국', '김치', '식용유')
    GROUP BY 1, 3
    ORDER BY 2 DESC
)

SELECT *
FROM SHORTLIST
GROUP BY 1
;