-- 코드를 입력하세요
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I LEFT JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
GROUP BY I.REST_ID
HAVING ADDRESS LIKE '서울%' AND
       ROUND(AVG(REVIEW_SCORE), 2) IS NOT NULL
ORDER BY SCORE DESC, FAVORITES DESC